### ISSUE TITLE
Remove files

### ISSUE THREAD

**Issue by Mte90** [raineorshine/yogini#2]
I have a boilerplate that works in the opposite of usually.
I have a full package where i replace stuff but also i need to delete files from it, so there is a way from the json file to remove a file that option is not flagged?

**Comment by raineorshine** [comment]
Thanks for your question! Sorry I didn't see it before. I'm working on rehabilitating the repo.

If you have a prompt `foo` defined in your `yogini.json` file...

```json
    {
      "type": "boolean",
      "name": "foo"
    }
```

...and you answer yes when running the generator, then `{foo}a.txt` will be copied as `a.txt` and `{!foo}b.txt` will not be copied at all.
